apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sq-ingress-devops
  namespace: devops-staging
  labels:
    app: SonarQube-devops
  annotations:
    kubernetes.io/ingress.class: tectonic
spec:
  rules:
  - host: sonarqube.devops.kube.example.com
    http:
      paths:
      - backend:
          serviceName: sq-svc-devops
          servicePort: 80
        path: /sonar
status:
  loadBalancer:
    ingress:
      - ip: 192.168.180.53
      - ip: 192.168.180.56
      - ip: 192.168.180.57
      - ip: 192.168.22.215
      - ip: 192.168.23.55
