apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sq-db-devops
spec:
  replicas: 1
  template:
    metadata:
      name: sq-db-devops
      labels:
        name: sq-db-devops
    spec:
      containers:
        - image: postgres:latest
          name: sq-db-devops
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd-devops
                  key: password
            - name: POSTGRES_USER
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            # This name must match the volumes.name below.
            - name: sqdb-data-devops
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: sqdb-data-devops
          persistentVolumeClaim:
            claimName: sqdb-claim-devops
