apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqdb-claim-devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqplugins-claim-devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
